let MenuConfig = {
  LIST_X: 50,
  LIST_Y: 500,
  LIST_ITEM_WIDTH: 300,
  LIST_ITEM_HEIGHT: 160,
  LIST_ITEM_XSPACE: 20,
  LIST_ITEM_YSPACE: 0,
  LIST_ITEM_COLOR: 0xff0000ff,
  MAINMENU_LIST_TYPE: 'vertical',
  LIST_BACKGROUND_WIDTH: 1920,
  LIST_BACKGROUND_HEIGHT: 230,
  LIST_BACKGROUND_Y: 470,
  LIST_BACKGROUND_X: 0,
  LIST_BACKGROUND_COLOR: 0x22f00000,
  LISTITEM_LABEL_X: 80,
  LISTITEM_LABEL_Y: 100,
  LISTITEM_TITLE_LABEL_X: 80,
  LISTITEM_TITLE_LABEL_Y: 20,
  LIST_TITLE: 'All Movies',
  LIST_TITLE_X: 50,
  LIST_TITLE_Y: 430
}

export default MenuConfig
