module.exports = {
  LIST_LABEL_FONTSIZE: 30,

  LIST_LINE_Y: 45,
  LIST_LINE_WIDTH: 730,
  LIST_LINE_HEIGHT: 3,

  LIST_ITEMS_Y: 60,

  LIST_ITEM_DEFAULT_WIDTH: 299,
  LIST_ITEM_DEFAULT_HEIGHT: 169,
  LIST_ITEM_ALPHA_FOCUSED: 1,
  LIST_ITEM_ALPHA_UNFOCUSED: 0.7,
  LIST_ITEM_BACKGROUND_WIDTH: 299,
  LIST_ITEM_BACKGROUND_HEIGHT: 168,
  LIST_ITEM_TITLE_Y: 175,
  LIST_ITEM_TITLE_WIDTH: 100,
  LIST_ITEM_TITLE_MAXLINES: 2,
  LIST_ITEM_TITLE_FONTSIZE: 18,
  LIST_ITEM_BORDER_FOCUSED: 6,
  LIST_ITEM_BORDER_UNFOCUSED: 0,

  CONTAINER_X: 100,
  CONTAINER_ALPHA: 0,
  CONTAINER_LIST_Y: 80,
  POPUP_X: 960,
  POPUP_Y: 540,
  POPUP_TIMEOUT: 2000,
}
