module.exports = {
  MENU_ITEM_FONTSIZE: 35,

  MENU_FOCUSFRAME_WIDTH: 10,
  MENU_FOCUSFRAME_FOCUS_HEIGHT: 8,
  MENU_FOCUSFRAME_UNFOCUS_HEIGHT: 0,
  MENU_FOCUSFRAME_MOUNT_Y: 1,

  MENU_ANIMATION_TIMEOUT: 500
}
