module.exports = {
  LOGO_MOUNT_X: 0.5,
  LOGO_MOUNT_Y: 1,
  LOGO_X: 960,
  LOGO_Y: 40,
  LOGO_WIDTH: 160,
  LOGO_HEIGHT: 39,
  LOGO_URL: 'cache/images/rdk-logo.png',

  INDICATOR_MOUNT_X: 0.5,
  INDICATOR_MOUNT_Y: 0.5,
  INDICATOR_X: 960,
  INDICATOR_Y: 600,
  INDICATOR_WIDTH: 110,
  INDICATOR_HEIGHT: 110,

  TEXT_MOUNT: 0.5,
  TEXT_X: 960,
  TEXT_Y: 720,
  TEXT_FONTSIZE: 32,
  TEXT_COLOR: 0xbbffffff
}
