module.exports = {
  TITLE_FONTSIZE: 32,
  LISTS_X: 150,
  LISTS_Y: 160,

  LIST_LABEL_FONTSIZE: 40,
  LIST_ITEMS_Y: 100,

  LIST_ITEM_DEFAULT_WIDTH: 300,
  LIST_ITEM_DEFAULT_HEIGHT: 170,

  ITEM_SHADE_ALPHA: 0.5,
  ITEM_TITLE_MOUNT_X: 0.5,
  ITEM_TITLE_MAXLINES: 1,
  ITEM_TITLE_FONTSIZE: 24
}
