module.exports = {
  PLAYERPROGRESS_BACKGROUND_HEIGHT: 170,
  PLAYERPROGRESS_BACKGROUND_URL: 'cache/images/channel-bar-bottom-gradient.png',

  PLAYERPROGRESS_CONTAINER_X: 100,
  PLAYERPROGRESS_CONTAINER_Y: 60,

  PLAYERPROGRESS_BAR_COLOR: 0xff2c4e68,
  PLAYERPROGRESS_BAR_ALPHA: 0.9,
  PLAYERPROGRESS_BAR_WIDTH: 1720,
  PLAYERPROGRESS_BAR_HEIGHT: 10,

  PLAYERPROGRESS_SCALE_COLOR: 0xff3489cd,
  PLAYERPROGRESS_SCALE_HEIGHT: 10,

  PLAYERPROGRESS_THUMB_Y: 5,
  PLAYERPROGRESS_THUMB_MOUNT: 0.5,
  PLAYERPROGRESS_THUMB_COLOR: 0xff3489cd,
  PLAYERPROGRESS_THUMB_RADIUS: 25,

  PLAYERPROGRESS_TITLE_X: 170,
  PLAYERPROGRESS_TITLE_FONTSIZE: 32,
}
