module.exports = {
  TIMELINE_WIDTH: 461,
  TIMELINE_HEIGHT: 6,
  TIMELINE_COLOR: 0xff3489cd,
  TIMELINE_BACKGROUND_COLOR: 0xff2c4e68,

  CHANNELBAR_HEIGHT: 240,
  CHANNELBAR_Y: 640,

  CHANNELBAR_BACKGROUND_GRADIENT_URL: 'cache/images/channel-bar-bottom-gradient.png',

  CHANNELBAR_CONTAINER_WIDTH: 225,
  CHANNELBAR_CONTAINER_HEIGHT: 100,
  CHANNELBAR_CONTAINER_Y: 60,

  CHANNELBAR_NUMBER_WIDTH: 40,
  CHANNELBAR_NUMBER_HEIGHT: 23,
  CHANNELBAR_NUMBER_FONTSIZE: 20,

  CHANNELBAR_LOGO_WIDTH: 80,
  CHANNELBAR_LOGO_HEIGHT: 60,

  CHANNELBAR_EPG_WIDTH: 600,
  CHANNELBAR_EPG_HEIGHT: 100,
  CHANNELBAR_EPG_Y: 60,

  CHANNELBAR_TITLE_WIDTH: 600,
  CHANNELBAR_TITLE_HEIGHT: 37,
  CHANNELBAR_TITLE_Y: 14,
  CHANNELBAR_TITLE_FONTSIZE: 20,

  CHANNELBAR_TIME_WIDTH: 600,
  CHANNELBAR_TIME_HEIGHT: 25,
  CHANNELBAR_TIME_Y: 56,
  CHANNELBAR_TIME_FONTSIZE: 20,

  CHANNELBAR_LINE_WIDTH: 461,
  CHANNELBAR_LINE_HEIGHT: 1,
  CHANNELBAR_LINE_Y: 100,
  CHANNELBAR_LINE_COLOR: 0xff3489cd
}
