module.exports = {
  TITLE_FONTSIZE: 32,
  CHANNELBAR_Y: 840,

  LOADINGINDICATOR_WIDTH: 110,
  LOADINGINDICATOR_HEIGHT: 110,
  LOADINGINDICATOR_X: 960,
  LOADINGINDICATOR_Y: 600,
  LOADINGINDICATOR_MOUNT_X: 0.5,
  LOADINGINDICATOR_MOUNT_Y: 0.5
}
