module.exports = {
  DIALOG_BACKGROUND_WIDTH: 600,
  DIALOG_BACKGROUND_HEIGHT: 230,
  DIALOG_BACKGROUND_MOUNT: 0.5,

  DIALOG_BORDER_WIDTH: 600,
  DIALOG_BORDER_HEIGHT: 230,
  DIALOG_BORDER_THICKNESS: 1,

  DIALOG_ICON_X: 20,
  DIALOG_ICON_Y: 20,
  DIALOG_ICON_WIDTH: 70,
  DIALOG_ICON_HEIGHT: 55,
  DIALOG_ICON_URL: 'cache/images/warning-sign.png',

  DIALOG_HEADER_X: 20,
  DIALOG_HEADER_Y: 20,
  DIALOG_HEADER_WIDTH: 560,
  DIALOG_HEADER_HEIGHT: 55,
  DIALOG_HEADER_FONTSIZE: 30,

  DIALOG_BODY_X: 20,
  DIALOG_BODY_Y: 115,
  DIALOG_BODY_WIDTH: 560,
  DIALOG_BODY_HEIGHT: 60,
  DIALOG_BODY_MAXLINES: 2,
  DIALOG_BODY_FONTSIZE: 25
}
