let MenuConfig = {
  MAINMENU_x: 150,
  MAINMENU_y: 730,
  MAINMENU_ITEM_WIDTH: 200,
  MAINMENU_ITEM_HEIGHT: 40,
  MAINMENU_ITEM_XSPACE: 400,
  MAINMENU_ITEM_YSPACE: 0,
  MAINMENU_ITEM_TXT_X: 0,
  MAINMENU_ITEM_TXT_Y: 0,
  MAINMENU_ITEM_COLOR: 0xff0000ff,
  MAINMENU_LIST_TYPE: 'vertical',
  SUBMENU_LIST_X: 0,
  SUBMENU_LIST_Y: 0,
  LIST_BACKGROUND_WIDTH: 1920,
  LIST_BACKGROUND_HEIGHT: 70
}

export default MenuConfig
