let MenuConfig = {
  MAINMENU_x: 150,
  MAINMENU_y: 730,
  MAINMENU_ITEM_WIDTH: 200,
  MAINMENU_ITEM_HEIGHT: 40,
  MAINMENU_ITEM_XSPACE: 400,
  MAINMENU_ITEM_YSPACE: 0,
  MAINMENU_ITEM_TXT_X: 0,
  MAINMENU_ITEM_TXT_Y: 0,
  MAINMENU_ITEM_COLOR: 0xff0000ff,
  MAINMENU_LIST_TYPE: 'vertical',
  SUBMENU_LIST_X: 0,
  SUBMENU_LIST_Y: 0,
  LIST_BACKGROUND_WIDTH: 1920,
  LIST_BACKGROUND_HEIGHT: 70,
  MAINMENU_LISTITEM_LABEL_X: 20,
  MAINMENU_LISTITEM_LABEL_Y: 0,
  MAINMENU_LISTITEM_IMG_X: 0,
  MAINMENU_LISTITEM_IMG_Y: 0,
  MAINMENU_LISTITEM_IMG_WIDTH: 200,
  MAINMENU_LISTITEM_IMG_HEIGHT: 200,
  MAINMENU_LIST_XSPACE: 400,
  MAINMENU_LIST_YSPACE: 0
}

export default MenuConfig
