let MenuConfig = {
  MAINMENU_x: 150,
  MAINMENU_y: 730,
  MAINMENU_ITEM_WIDTH: 200,
  MAINMENU_ITEM_HEIGHT: 40,
  MAINMENU_ITEM_XSPACE: 400,
  MAINMENU_ITEM_YSPACE: 0,
  MAINMENU_ITEM_TXT_X: 0,
  MAINMENU_ITEM_TXT_Y: 0,
  MAINMENU_ITEM_COLOR: 0xff0000ff,
  MAINMENU_LIST_TYPE: 'vertical'
}

export default MenuConfig
